import { Vector3 } from 'three';

export type VehicleSystem =
  | 'structural'
  | 'body'
  | 'lighting'
  | 'interior'
  | 'wheels'
  | 'brakes'
  | 'suspension'
  | 'powertrain'
  | 'thermal'
  | 'glass';

export interface ComponentMetadata {
  id: string;
  displayName: string;
  category: VehicleSystem;
  description: string;
  technicalRole: string;
  materialType: string;
  status: string;
}

export interface ExplodedOffset {
  position: Vector3;
  rotation?: Vector3;
}

export interface VehicleComponentData {
  id: string;
  displayName: string;
  category: VehicleSystem;
  objectName: string;
  defaultPosition: [number, number, number];
  defaultRotation: [number, number, number];
  defaultScale: [number, number, number];
  explodedOffset: [number, number, number];
  description: string;
  technicalRole: string;
  materialType: string;
}

export interface VehicleState {
  selectedComponent: string | null;
  exploded: boolean;
  xrayMode: boolean;
  activeSystemFilter: VehicleSystem | 'all';
  doorsOpen: boolean;
  hoodOpen: boolean;
  trunkOpen: boolean;
  lightsEnabled: boolean;
  roofTint: 'clear' | 'tinted' | 'dark';
  activeCameraPreset: string;
  inspectMode: boolean;
  animationProgress: Record<string, number>;
}

export const VEHICLE_COMPONENTS: VehicleComponentData[] = [
  {
    id: 'chassis',
    displayName: 'Monocoque Chassis',
    category: 'structural',
    objectName: 'vehicle_chassis',
    defaultPosition: [0, 0.35, 0],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [0, -1.2, 0],
    description: 'Carbon fiber structural monocoque. Primary load-bearing structure integrating battery skateboard platform.',
    technicalRole: 'Structural Integrity / Safety Cell',
    materialType: 'carbon_fiber',
  },
  {
    id: 'frontCrashStructure',
    displayName: 'Front Crash Structure',
    category: 'structural',
    objectName: 'vehicle_front_crash_structure',
    defaultPosition: [0, 0.3, -1.9],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [0, -0.5, -2],
    description: 'Aluminum front crash structure with energy-absorbing crumple zones.',
    technicalRole: 'Frontal Impact Protection',
    materialType: 'anodized_metal',
  },
  {
    id: 'rearFrame',
    displayName: 'Rear Structural Frame',
    category: 'structural',
    objectName: 'vehicle_rear_frame',
    defaultPosition: [0, 0.35, 1.8],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [0, -0.5, 2],
    description: 'Rear subframe supporting motor, suspension, and diffuser assembly.',
    technicalRole: 'Rear Structural Support',
    materialType: 'anodized_metal',
  },
  {
    id: 'underbodyPanel',
    displayName: 'Underbody Aero Panel',
    category: 'structural',
    objectName: 'vehicle_underbody_panel',
    defaultPosition: [0, 0.15, 0],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [0, -1.5, 0],
    description: 'Flat carbon fiber underbody panel for optimized aerodynamic ground effect.',
    technicalRole: 'Underbody Aerodynamics',
    materialType: 'carbon_fiber',
  },
  {
    id: 'frontBodyShell',
    displayName: 'Front Body Shell',
    category: 'body',
    objectName: 'vehicle_front_body',
    defaultPosition: [0, 0.6, -1.5],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [0, 0.8, -2.5],
    description: 'Sculpted front body panel with integrated cooling ducts and aero channels.',
    technicalRole: 'Front Aerodynamics / Styling',
    materialType: 'car_paint',
  },
  {
    id: 'midBodyShell',
    displayName: 'Mid Body Shell',
    category: 'body',
    objectName: 'vehicle_mid_body',
    defaultPosition: [0, 0.7, 0],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [0, 1, 0],
    description: 'Central body structure integrating door sills and roof rail connections.',
    technicalRole: 'Central Structural Shell',
    materialType: 'car_paint',
  },
  {
    id: 'rearBodyShell',
    displayName: 'Rear Body Shell',
    category: 'body',
    objectName: 'vehicle_rear_body',
    defaultPosition: [0, 0.55, 1.5],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [0, 0.8, 2.5],
    description: 'Rear body panel with muscular haunches and integrated aero elements.',
    technicalRole: 'Rear Aerodynamics / Styling',
    materialType: 'car_paint',
  },
  {
    id: 'hood',
    displayName: 'Articulating Hood',
    category: 'body',
    objectName: 'vehicle_hood',
    defaultPosition: [0, 0.82, -1.3],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [0, 1.5, -2],
    description: 'Front-hinged lightweight aluminum hood with active aero venting.',
    technicalRole: 'Front Access Panel',
    materialType: 'car_paint',
  },
  {
    id: 'trunk',
    displayName: 'Rear Trunk Lid',
    category: 'body',
    objectName: 'vehicle_trunk',
    defaultPosition: [0, 0.85, 1.4],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [0, 1.5, 2.5],
    description: 'Power-operated rear trunk lid with integrated active spoiler.',
    technicalRole: 'Rear Storage Access',
    materialType: 'car_paint',
  },
  {
    id: 'doorLeft',
    displayName: 'Left Gullwing Door',
    category: 'body',
    objectName: 'vehicle_door_left',
    defaultPosition: [-0.95, 0.65, -0.1],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [-2, 0.5, 0],
    description: 'Left-side gullwing door with frameless glass and soft-close mechanism.',
    technicalRole: 'Left Entry / Egress',
    materialType: 'car_paint',
  },
  {
    id: 'doorRight',
    displayName: 'Right Gullwing Door',
    category: 'body',
    objectName: 'vehicle_door_right',
    defaultPosition: [0.95, 0.65, -0.1],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [2, 0.5, 0],
    description: 'Right-side gullwing door with frameless glass and soft-close mechanism.',
    technicalRole: 'Right Entry / Egress',
    materialType: 'car_paint',
  },
  {
    id: 'frontBumper',
    displayName: 'Front Bumper',
    category: 'body',
    objectName: 'vehicle_front_bumper',
    defaultPosition: [0, 0.35, -2.15],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [0, 0, -3],
    description: 'Front bumper assembly with integrated cooling intakes and sensor array.',
    technicalRole: 'Front Impact Protection / Cooling',
    materialType: 'car_paint',
  },
  {
    id: 'frontSplitter',
    displayName: 'Active Front Splitter',
    category: 'body',
    objectName: 'vehicle_front_splitter',
    defaultPosition: [0, 0.18, -2.1],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [0, -0.5, -3],
    description: 'Active front aerodynamic splitter with adjustable downforce angle.',
    technicalRole: 'Front Downforce Generation',
    materialType: 'carbon_fiber',
  },
  {
    id: 'rearBumper',
    displayName: 'Rear Bumper',
    category: 'body',
    objectName: 'vehicle_rear_bumper',
    defaultPosition: [0, 0.35, 2.15],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [0, 0, 3],
    description: 'Rear bumper with integrated thermal extraction vents.',
    technicalRole: 'Rear Impact Protection',
    materialType: 'car_paint',
  },
  {
    id: 'rearDiffuser',
    displayName: 'Carbon Fiber Rear Diffuser',
    category: 'body',
    objectName: 'vehicle_rear_diffuser',
    defaultPosition: [0, 0.15, 2.0],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [0, -0.5, 3],
    description: 'Full-width carbon fiber rear diffuser with vortex generators.',
    technicalRole: 'Rear Downforce / Airflow Management',
    materialType: 'carbon_fiber',
  },
  {
    id: 'roof',
    displayName: 'Panoramic Solar Roof',
    category: 'glass',
    objectName: 'vehicle_roof',
    defaultPosition: [0, 1.1, -0.1],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [0, 2, 0],
    description: 'Panoramic electrochromic solar glass roof with integrated photovoltaic cells.',
    technicalRole: 'Cabin Enclosure / Energy Harvesting',
    materialType: 'glass',
  },
  {
    id: 'headlightLeft',
    displayName: 'Left LED Projector Headlight',
    category: 'lighting',
    objectName: 'vehicle_headlight_left',
    defaultPosition: [-0.7, 0.5, -2.15],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [-1, 0.5, -2],
    description: 'Left adaptive LED matrix projector headlight with ADB functionality.',
    technicalRole: 'Forward Illumination',
    materialType: 'led_emissive',
  },
  {
    id: 'headlightRight',
    displayName: 'Right LED Projector Headlight',
    category: 'lighting',
    objectName: 'vehicle_headlight_right',
    defaultPosition: [0.7, 0.5, -2.15],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [1, 0.5, -2],
    description: 'Right adaptive LED matrix projector headlight with ADB functionality.',
    technicalRole: 'Forward Illumination',
    materialType: 'led_emissive',
  },
  {
    id: 'drlLeft',
    displayName: 'Left DRL Strip',
    category: 'lighting',
    objectName: 'vehicle_drl_left',
    defaultPosition: [-0.8, 0.45, -2.1],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [-1.2, 0.3, -2],
    description: 'Left signature LED daytime running light strip.',
    technicalRole: 'Daytime Visibility',
    materialType: 'led_emissive',
  },
  {
    id: 'drlRight',
    displayName: 'Right DRL Strip',
    category: 'lighting',
    objectName: 'vehicle_drl_right',
    defaultPosition: [0.8, 0.45, -2.1],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [1.2, 0.3, -2],
    description: 'Right signature LED daytime running light strip.',
    technicalRole: 'Daytime Visibility',
    materialType: 'led_emissive',
  },
  {
    id: 'rearLightBar',
    displayName: 'OLED Rear Light Bar',
    category: 'lighting',
    objectName: 'vehicle_rear_lightbar',
    defaultPosition: [0, 0.55, 2.2],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [0, 0.5, 2],
    description: 'Full-width OLED rear light bar with animated startup sequence.',
    technicalRole: 'Rear Visibility / Signaling',
    materialType: 'led_emissive',
  },
  {
    id: 'indicatorLeft',
    displayName: 'Left Sequential Indicator',
    category: 'lighting',
    objectName: 'vehicle_indicator_left',
    defaultPosition: [-0.9, 0.45, -2.0],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [-1.2, 0.2, -1.5],
    description: 'Left sequential LED turn indicator with sweep animation.',
    technicalRole: 'Turn Signaling',
    materialType: 'led_emissive',
  },
  {
    id: 'indicatorRight',
    displayName: 'Right Sequential Indicator',
    category: 'lighting',
    objectName: 'vehicle_indicator_right',
    defaultPosition: [0.9, 0.45, -2.0],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [1.2, 0.2, -1.5],
    description: 'Right sequential LED turn indicator with sweep animation.',
    technicalRole: 'Turn Signaling',
    materialType: 'led_emissive',
  },
  {
    id: 'dashboard',
    displayName: 'Digital Dashboard',
    category: 'interior',
    objectName: 'vehicle_dashboard',
    defaultPosition: [0, 0.7, -1.2],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [0, 1.5, -1.5],
    description: 'Minimalist digital dashboard with OLED display integration.',
    technicalRole: 'Driver Information Display',
    materialType: 'dark_plastic',
  },
  {
    id: 'instrumentCluster',
    displayName: 'Instrument Cluster',
    category: 'interior',
    objectName: 'vehicle_instrument_cluster',
    defaultPosition: [0, 0.85, -1.1],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [0, 2, -1.5],
    description: '12.3" curved OLED instrument cluster with real-time telemetry.',
    technicalRole: 'Vehicle Telemetry Display',
    materialType: 'dark_plastic',
  },
  {
    id: 'hud',
    displayName: 'HUD Display',
    category: 'interior',
    objectName: 'vehicle_hud',
    defaultPosition: [0, 0.95, -1.0],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [0, 2.5, -1],
    description: 'Augmented reality head-up display projecting onto windshield.',
    technicalRole: 'AR Navigation / Speed Display',
    materialType: 'led_emissive',
  },
  {
    id: 'steeringWheel',
    displayName: 'Steering Wheel',
    category: 'interior',
    objectName: 'vehicle_steering_wheel',
    defaultPosition: [0, 0.75, -0.85],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [0, 2, -1],
    description: 'Yoke-style steering wheel with integrated controls and haptic feedback.',
    technicalRole: 'Vehicle Direction Control',
    materialType: 'leather',
  },
  {
    id: 'steeringColumn',
    displayName: 'Steering Column',
    category: 'interior',
    objectName: 'vehicle_steering_column',
    defaultPosition: [0, 0.65, -1.0],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [0, 1.5, -1],
    description: 'Electrically adjustable steering column with memory function.',
    technicalRole: 'Steering Mechanism',
    materialType: 'brushed_aluminum',
  },
  {
    id: 'seatDriver',
    displayName: 'Driver Carbon Fiber Bucket Seat',
    category: 'interior',
    objectName: 'vehicle_seat_driver',
    defaultPosition: [-0.4, 0.5, -0.2],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [-0.5, 2, 0],
    description: 'Full carbon fiber bucket seat with Alcantara upholstery and heating.',
    technicalRole: 'Driver Positioning / Safety',
    materialType: 'carbon_fiber',
  },
  {
    id: 'seatPassenger',
    displayName: 'Passenger Carbon Fiber Bucket Seat',
    category: 'interior',
    objectName: 'vehicle_seat_passenger',
    defaultPosition: [0.4, 0.5, -0.2],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [0.5, 2, 0],
    description: 'Passenger carbon fiber bucket seat matching driver configuration.',
    technicalRole: 'Passenger Positioning / Safety',
    materialType: 'carbon_fiber',
  },
  {
    id: 'centerConsole',
    displayName: 'Center Console',
    category: 'interior',
    objectName: 'vehicle_center_console',
    defaultPosition: [0, 0.45, -0.3],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [0, 1.5, 0],
    description: 'Floating center console with wireless charging and haptic controls.',
    technicalRole: 'Interior Controls / Storage',
    materialType: 'dark_plastic',
  },
  {
    id: 'interiorDashboard',
    displayName: 'Interior Dashboard Structure',
    category: 'interior',
    objectName: 'vehicle_interior_dashboard',
    defaultPosition: [0, 0.6, -1.15],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [0, 1, -2],
    description: 'Full dashboard structure with premium soft-touch materials and ambient lighting.',
    technicalRole: 'Interior Structural Framework',
    materialType: 'leather',
  },
  {
    id: 'doorPanelLeft',
    displayName: 'Left Interior Door Panel',
    category: 'interior',
    objectName: 'vehicle_door_panel_left',
    defaultPosition: [-0.85, 0.55, -0.1],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [-2.5, 0.5, 0],
    description: 'Left interior door panel with ambient LED lighting and Alcantara trim.',
    technicalRole: 'Left Interior Trim',
    materialType: 'alcantara',
  },
  {
    id: 'doorPanelRight',
    displayName: 'Right Interior Door Panel',
    category: 'interior',
    objectName: 'vehicle_door_panel_right',
    defaultPosition: [0.85, 0.55, -0.1],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [2.5, 0.5, 0],
    description: 'Right interior door panel with ambient LED lighting and Alcantara trim.',
    technicalRole: 'Right Interior Trim',
    materialType: 'alcantara',
  },
  {
    id: 'wheelFL',
    displayName: 'Front Left Alloy Wheel',
    category: 'wheels',
    objectName: 'vehicle_wheel_fl',
    defaultPosition: [-0.82, 0.34, -1.4],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [-1.5, 0, -0.5],
    description: '21" forged aluminum alloy wheel, multi-spoke design.',
    technicalRole: 'Front Left Rolling Contact',
    materialType: 'brushed_aluminum',
  },
  {
    id: 'wheelFR',
    displayName: 'Front Right Alloy Wheel',
    category: 'wheels',
    objectName: 'vehicle_wheel_fr',
    defaultPosition: [0.82, 0.34, -1.4],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [1.5, 0, -0.5],
    description: '21" forged aluminum alloy wheel, multi-spoke design.',
    technicalRole: 'Front Right Rolling Contact',
    materialType: 'brushed_aluminum',
  },
  {
    id: 'wheelRL',
    displayName: 'Rear Left Alloy Wheel',
    category: 'wheels',
    objectName: 'vehicle_wheel_rl',
    defaultPosition: [-0.81, 0.34, 1.4],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [-1.5, 0, 0.5],
    description: '22" forged aluminum alloy wheel, wider rear specification.',
    technicalRole: 'Rear Left Rolling Contact',
    materialType: 'brushed_aluminum',
  },
  {
    id: 'wheelRR',
    displayName: 'Rear Right Alloy Wheel',
    category: 'wheels',
    objectName: 'vehicle_wheel_rr',
    defaultPosition: [0.81, 0.34, 1.4],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [1.5, 0, 0.5],
    description: '22" forged aluminum alloy wheel, wider rear specification.',
    technicalRole: 'Rear Right Rolling Contact',
    materialType: 'brushed_aluminum',
  },
  {
    id: 'tireFL',
    displayName: 'Front Left Tire',
    category: 'wheels',
    objectName: 'vehicle_tire_fl',
    defaultPosition: [-0.82, 0.34, -1.4],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [-1.8, 0, -0.5],
    description: 'Michelin Pilot Sport EV 255/35 R21 ultra-high-performance tire.',
    technicalRole: 'Front Left Traction',
    materialType: 'tire_rubber',
  },
  {
    id: 'tireFR',
    displayName: 'Front Right Tire',
    category: 'wheels',
    objectName: 'vehicle_tire_fr',
    defaultPosition: [0.82, 0.34, -1.4],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [1.8, 0, -0.5],
    description: 'Michelin Pilot Sport EV 255/35 R21 ultra-high-performance tire.',
    technicalRole: 'Front Right Traction',
    materialType: 'tire_rubber',
  },
  {
    id: 'tireRL',
    displayName: 'Rear Left Tire',
    category: 'wheels',
    objectName: 'vehicle_tire_rl',
    defaultPosition: [-0.81, 0.34, 1.4],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [-1.8, 0, 0.5],
    description: 'Michelin Pilot Sport EV 305/30 R22 ultra-high-performance rear tire.',
    technicalRole: 'Rear Left Traction',
    materialType: 'tire_rubber',
  },
  {
    id: 'tireRR',
    displayName: 'Rear Right Tire',
    category: 'wheels',
    objectName: 'vehicle_tire_rr',
    defaultPosition: [0.81, 0.34, 1.4],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [1.8, 0, 0.5],
    description: 'Michelin Pilot Sport EV 305/30 R22 ultra-high-performance rear tire.',
    technicalRole: 'Rear Right Traction',
    materialType: 'tire_rubber',
  },
  {
    id: 'brakeDiscFL',
    displayName: 'Front Left Carbon-Ceramic Brake Disc',
    category: 'brakes',
    objectName: 'vehicle_brake_disc_fl',
    defaultPosition: [-0.82, 0.34, -1.35],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [-1.3, 0, -0.5],
    description: '420mm carbon-ceramic brake disc with ventilated cross-drilled pattern.',
    technicalRole: 'Front Left Deceleration',
    materialType: 'brake_ceramic',
  },
  {
    id: 'brakeDiscFR',
    displayName: 'Front Right Carbon-Ceramic Brake Disc',
    category: 'brakes',
    objectName: 'vehicle_brake_disc_fr',
    defaultPosition: [0.82, 0.34, -1.35],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [1.3, 0, -0.5],
    description: '420mm carbon-ceramic brake disc with ventilated cross-drilled pattern.',
    technicalRole: 'Front Right Deceleration',
    materialType: 'brake_ceramic',
  },
  {
    id: 'brakeDiscRL',
    displayName: 'Rear Left Carbon-Ceramic Brake Disc',
    category: 'brakes',
    objectName: 'vehicle_brake_disc_rl',
    defaultPosition: [-0.81, 0.34, 1.35],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [-1.3, 0, 0.5],
    description: '380mm carbon-ceramic brake disc with ventilated design.',
    technicalRole: 'Rear Left Deceleration',
    materialType: 'brake_ceramic',
  },
  {
    id: 'brakeDiscRR',
    displayName: 'Rear Right Carbon-Ceramic Brake Disc',
    category: 'brakes',
    objectName: 'vehicle_brake_disc_rr',
    defaultPosition: [0.81, 0.34, 1.35],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [1.3, 0, 0.5],
    description: '380mm carbon-ceramic brake disc with ventilated design.',
    technicalRole: 'Rear Right Deceleration',
    materialType: 'brake_ceramic',
  },
  {
    id: 'caliperFL',
    displayName: 'Front Left Multi-Piston Caliper',
    category: 'brakes',
    objectName: 'vehicle_caliper_fl',
    defaultPosition: [-0.82, 0.34, -1.35],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [-1.1, 0.3, -0.5],
    description: '6-piston monobloc aluminum caliper with carbon ceramic pads.',
    technicalRole: 'Front Left Brake Actuation',
    materialType: 'anodized_metal',
  },
  {
    id: 'caliperFR',
    displayName: 'Front Right Multi-Piston Caliper',
    category: 'brakes',
    objectName: 'vehicle_caliper_fr',
    defaultPosition: [0.82, 0.34, -1.35],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [1.1, 0.3, -0.5],
    description: '6-piston monobloc aluminum caliper with carbon ceramic pads.',
    technicalRole: 'Front Right Brake Actuation',
    materialType: 'anodized_metal',
  },
  {
    id: 'caliperRL',
    displayName: 'Rear Left Multi-Piston Caliper',
    category: 'brakes',
    objectName: 'vehicle_caliper_rl',
    defaultPosition: [-0.81, 0.34, 1.35],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [-1.1, 0.3, 0.5],
    description: '4-piston monobloc aluminum caliper.',
    technicalRole: 'Rear Left Brake Actuation',
    materialType: 'anodized_metal',
  },
  {
    id: 'caliperRR',
    displayName: 'Rear Right Multi-Piston Caliper',
    category: 'brakes',
    objectName: 'vehicle_caliper_rr',
    defaultPosition: [0.81, 0.34, 1.35],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [1.1, 0.3, 0.5],
    description: '4-piston monobloc aluminum caliper.',
    technicalRole: 'Rear Right Brake Actuation',
    materialType: 'anodized_metal',
  },
  {
    id: 'shockFL',
    displayName: 'Front Left Shock Absorber',
    category: 'suspension',
    objectName: 'vehicle_shock_fl',
    defaultPosition: [-0.7, 0.5, -1.4],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [-1.5, 0.3, -0.8],
    description: 'Adaptive air suspension damper with electronically controlled valving.',
    technicalRole: 'Front Left Ride Control',
    materialType: 'anodized_metal',
  },
  {
    id: 'shockFR',
    displayName: 'Front Right Shock Absorber',
    category: 'suspension',
    objectName: 'vehicle_shock_fr',
    defaultPosition: [0.7, 0.5, -1.4],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [1.5, 0.3, -0.8],
    description: 'Adaptive air suspension damper with electronically controlled valving.',
    technicalRole: 'Front Right Ride Control',
    materialType: 'anodized_metal',
  },
  {
    id: 'shockRL',
    displayName: 'Rear Left Shock Absorber',
    category: 'suspension',
    objectName: 'vehicle_shock_rl',
    defaultPosition: [-0.7, 0.5, 1.4],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [-1.5, 0.3, 0.8],
    description: 'Adaptive air suspension damper with ride height control.',
    technicalRole: 'Rear Left Ride Control',
    materialType: 'anodized_metal',
  },
  {
    id: 'shockRR',
    displayName: 'Rear Right Shock Absorber',
    category: 'suspension',
    objectName: 'vehicle_shock_rr',
    defaultPosition: [0.7, 0.5, 1.4],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [1.5, 0.3, 0.8],
    description: 'Adaptive air suspension damper with ride height control.',
    technicalRole: 'Rear Right Ride Control',
    materialType: 'anodized_metal',
  },
  {
    id: 'suspensionFront',
    displayName: 'Front Suspension Assembly',
    category: 'suspension',
    objectName: 'vehicle_suspension_front',
    defaultPosition: [0, 0.3, -1.4],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [0, -0.3, -1.5],
    description: 'Double-wishbone front suspension with pushrod-actuated dampers.',
    technicalRole: 'Front Axle Geometry Control',
    materialType: 'anodized_metal',
  },
  {
    id: 'suspensionRear',
    displayName: 'Rear Suspension Assembly',
    category: 'suspension',
    objectName: 'vehicle_suspension_rear',
    defaultPosition: [0, 0.3, 1.4],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [0, -0.3, 1.5],
    description: 'Multi-link rear suspension with active anti-roll system.',
    technicalRole: 'Rear Axle Geometry Control',
    materialType: 'anodized_metal',
  },
  {
    id: 'batteryPack',
    displayName: 'High-Voltage Battery Pack',
    category: 'powertrain',
    objectName: 'vehicle_battery_pack',
    defaultPosition: [0, 0.18, 0],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [0, -2, 0],
    description: '100 kWh lithium-ion battery pack with 800V architecture. Multi-module design with integrated thermal management.',
    technicalRole: 'Energy Storage',
    materialType: 'battery_metal',
  },
  {
    id: 'motorFront',
    displayName: 'Front Electric Motor',
    category: 'powertrain',
    objectName: 'vehicle_motor_front',
    defaultPosition: [0, 0.3, -1.4],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [0, 0.3, -2.5],
    description: '250 kW permanent magnet synchronous motor with silicon carbide inverter.',
    technicalRole: 'Front Propulsion',
    materialType: 'anodized_metal',
  },
  {
    id: 'motorRear',
    displayName: 'Rear Electric Motor',
    category: 'powertrain',
    objectName: 'vehicle_motor_rear',
    defaultPosition: [0, 0.3, 1.4],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [0, 0.3, 2.5],
    description: '450 kW permanent magnet synchronous motor with torque vectoring capability.',
    technicalRole: 'Rear Propulsion',
    materialType: 'anodized_metal',
  },
  {
    id: 'transmissionFront',
    displayName: 'Front Single-Speed Transmission',
    category: 'powertrain',
    objectName: 'vehicle_transmission_front',
    defaultPosition: [0, 0.3, -1.5],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [-0.5, 0.3, -3],
    description: 'Single-speed reduction gearbox, 9.5:1 ratio.',
    technicalRole: 'Front Torque Delivery',
    materialType: 'anodized_metal',
  },
  {
    id: 'transmissionRear',
    displayName: 'Rear Single-Speed Transmission',
    category: 'powertrain',
    objectName: 'vehicle_transmission_rear',
    defaultPosition: [0, 0.3, 1.5],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [0.5, 0.3, 3],
    description: 'Single-speed reduction gearbox, 9.0:1 ratio with limited-slip differential.',
    technicalRole: 'Rear Torque Delivery',
    materialType: 'anodized_metal',
  },
  {
    id: 'coolingIntakeLeft',
    displayName: 'Left Cooling Intake',
    category: 'thermal',
    objectName: 'vehicle_cooling_intake_left',
    defaultPosition: [-0.6, 0.3, -2.1],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [-1, 0, -1],
    description: 'Left-side radiator cooling intake with active grille shutter.',
    technicalRole: 'Left Thermal Management',
    materialType: 'dark_plastic',
  },
  {
    id: 'coolingIntakeRight',
    displayName: 'Right Cooling Intake',
    category: 'thermal',
    objectName: 'vehicle_cooling_intake_right',
    defaultPosition: [0.6, 0.3, -2.1],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [1, 0, -1],
    description: 'Right-side radiator cooling intake with active grille shutter.',
    technicalRole: 'Right Thermal Management',
    materialType: 'dark_plastic',
  },
  {
    id: 'coolingDuctFront',
    displayName: 'Front Cooling Duct',
    category: 'thermal',
    objectName: 'vehicle_cooling_duct_front',
    defaultPosition: [0, 0.25, -2.0],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [0, -0.5, -1.5],
    description: 'Central front cooling duct directing airflow to battery and motor radiators.',
    technicalRole: 'Front Airflow Distribution',
    materialType: 'dark_plastic',
  },
  {
    id: 'coolingDuctRear',
    displayName: 'Rear Cooling Duct',
    category: 'thermal',
    objectName: 'vehicle_cooling_duct_rear',
    defaultPosition: [0, 0.2, 2.0],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [0, -0.5, 1.5],
    description: 'Rear thermal extraction duct for motor and inverter cooling.',
    technicalRole: 'Rear Heat Extraction',
    materialType: 'dark_plastic',
  },
  {
    id: 'windshield',
    displayName: 'Front Windshield',
    category: 'glass',
    objectName: 'vehicle_windshield',
    defaultPosition: [0, 0.9, -0.85],
    defaultRotation: [-0.35, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [0, 1.5, -1.5],
    description: 'Laminated acoustic glass windshield with HUD projection zone and rain sensor.',
    technicalRole: 'Front Visibility / Acoustic Isolation',
    materialType: 'glass',
  },
  {
    id: 'rearGlass',
    displayName: 'Rear Glass',
    category: 'glass',
    objectName: 'vehicle_rear_glass',
    defaultPosition: [0, 0.85, 1.3],
    defaultRotation: [0.4, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [0, 1.5, 2],
    description: 'Heated rear glass with integrated antenna and defogger.',
    technicalRole: 'Rear Visibility',
    materialType: 'glass',
  },
  {
    id: 'windowLeft',
    displayName: 'Left Side Window',
    category: 'glass',
    objectName: 'vehicle_window_left',
    defaultPosition: [-0.92, 0.8, -0.1],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [-2, 1, 0],
    description: 'Left frameless side window with acoustic lamination.',
    technicalRole: 'Left Side Visibility',
    materialType: 'glass',
  },
  {
    id: 'windowRight',
    displayName: 'Right Side Window',
    category: 'glass',
    objectName: 'vehicle_window_right',
    defaultPosition: [0.92, 0.8, -0.1],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [2, 1, 0],
    description: 'Right frameless side window with acoustic lamination.',
    technicalRole: 'Right Side Visibility',
    materialType: 'glass',
  },
  {
    id: 'mirrorLeft',
    displayName: 'Left Digital Mirror Camera',
    category: 'glass',
    objectName: 'vehicle_mirror_left',
    defaultPosition: [-0.95, 0.85, -0.6],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [-1.5, 1, -0.5],
    description: 'Left digital side mirror camera system replacing traditional mirrors.',
    technicalRole: 'Left Rear Visibility',
    materialType: 'dark_plastic',
  },
  {
    id: 'mirrorRight',
    displayName: 'Right Digital Mirror Camera',
    category: 'glass',
    objectName: 'vehicle_mirror_right',
    defaultPosition: [0.95, 0.85, -0.6],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [1.5, 1, -0.5],
    description: 'Right digital side mirror camera system replacing traditional mirrors.',
    technicalRole: 'Right Rear Visibility',
    materialType: 'dark_plastic',
  },
  {
    id: 'mirrorHousingLeft',
    displayName: 'Left Camera Housing',
    category: 'glass',
    objectName: 'vehicle_mirror_housing_left',
    defaultPosition: [-0.98, 0.85, -0.6],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [-1.8, 1, -0.5],
    description: 'Aerodynamic housing for left digital mirror camera.',
    technicalRole: 'Left Camera Enclosure',
    materialType: 'dark_plastic',
  },
  {
    id: 'mirrorHousingRight',
    displayName: 'Right Camera Housing',
    category: 'glass',
    objectName: 'vehicle_mirror_housing_right',
    defaultPosition: [0.98, 0.85, -0.6],
    defaultRotation: [0, 0, 0],
    defaultScale: [1, 1, 1],
    explodedOffset: [1.8, 1, -0.5],
    description: 'Aerodynamic housing for right digital mirror camera.',
    technicalRole: 'Right Camera Enclosure',
    materialType: 'dark_plastic',
  },
];
